/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#171c20",
        "surface-bright": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "surface": "#4A0E17",
        "surface-container-low": "#3d0b13",
        "on-surface-variant": "#d4c1a2",
        "on-tertiary-fixed-variant": "#42474c",
        "on-primary": "#ffffff",
        "surface-container": "#f8efe1",
        "secondary-fixed": "#d4af37",
        "brand-gold": "#D4AF37",
        "brand-burgundy": "#4A0E17",
        "on-primary-container": "#7a8593",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "outline": "#75777c",
        "background": "#4A0E17",
        "on-tertiary-container": "#7f848a",
        "error": "#ba1a1a",
        "surface-tint": "#555f6d",
        "on-surface-muted": "#44474b",
        "on-secondary-container": "#785a26",
        "secondary-container": "#fdd494",
        "outline-variant": "#c4c6cc",
        "tertiary-fixed-dim": "#c2c7cd",
        "surface-container-high": "#e7e8e9",
        "surface-dark": "#0b1621",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5d420f",
        "hero-overlay": "rgba(0,0,0,0.4)",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#171c20",
        "tertiary": "#000000",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#3d4854",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#bcc7d7",
        "secondary-fixed-dim": "#e8c082",
        "on-secondary-fixed": "#281900",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#dee3e9",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d8e3f3",
        "on-error-container": "#93000a",
        "primary": "#000000",
        "primary-container": "#121c28",
        "inverse-primary": "#bcc7d7",
        "on-primary-fixed": "#121c28",
        "on-error": "#ffffff",
        "secondary": "#775925",
        "on-surface": "#191c1d"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "element-gap": "16px",
        "section-gap": "120px",
        "container-max": "1280px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "arabic-serif": ["Noto Serif Arabic", "Noto Kufi Arabic", "serif"],
        "label-md": ["Inter", "Noto Serif Arabic", "Noto Kufi Arabic", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "Noto Serif Arabic", "Noto Kufi Arabic", "sans-serif"],
        "body-md": ["Inter", "Noto Serif Arabic", "Noto Kufi Arabic", "sans-serif"],
        "body-lg": ["Inter", "Noto Serif Arabic", "Noto Kufi Arabic", "sans-serif"],
        "headline-md": ["Inter", "Noto Serif Arabic", "Noto Kufi Arabic", "sans-serif"],
        "headline-xl": ["Inter", "Noto Serif Arabic", "Noto Kufi Arabic", "sans-serif"],
        "headline-xl-mobile": ["Inter", "Noto Serif Arabic", "Noto Kufi Arabic", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg-mobile": ["72px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "400" }],
        "display-lg": ["120px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "300" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
